{ pkgs, ... }:

{
  # See this for further reading and improvements: https://hoverbear.org/blog/declarative-gnome-configuration-in-nixos/
  services.xserver.desktopManager.gnome = {
    extraGSettingsOverrides =
      "    # Change default screensaver settings\n    [org.gnome.desktop.screensaver]\n    lock-enabled=true\n\n    [org.gnome.desktop.wm.preferences]\n    audible-bell=false\n    resize-with-right-button=true\n\n    [org.gnome.desktop.input-sources]\n    sources=[('xkb', 'pt')]\n    xkb-options=['terminate:ctrl_alt_bksp']\n\n    [org.gnome.desktop.interface]\n    gtk-enable-primary-paste=false\n    show-battery-percentage=false\n    text-scaling-factor=1.25\n    show-battery-percentage=false\n\n    [org.gnome.shell]\n    disabled-extensions=['apps-menu@gnome-shell-extensions.gcampax.github.com', 'auto-move-windows@gnome-shell-extensions.gcampax.github.com', 'places-menu@gnome-shell-extensions.gcampax.github.com', 'native-window-placement@gnome-shell-extensions.gcampax.github.com', 'window-list@gnome-shell-extensions.gcampax.github.com', 'workspace-indicator@gnome-shell-extensions.gcampax.github.com']\n    disable-user-extensions=false\n    enabled-extensions=['caffeine@patapon.info', 'clipboard-history@alexsaveau.dev', 'gsconnect@andyholmes.github.io', 'blur-my-shell@aunetx']\n    favorite-apps=['firefox.desktop', 'org.gnome.Nautilus.desktop', 'spotify.desktop']\n    remember-mount-password=false\n\n    [org.gnome.shell.weather]\n    automatic-location=true\n    locations=[<(uint32 2, <('Lisbon', 'LPPT', true, [(0.6766059791742326, -0.15940673253105125)], [(0.67573331454823549, -0.15940673253105125)])>)>]\n\n    [org.gnome.shell.window-switcher]\n    current-workspace-only=true\n\n    [org.gnome.shell.extensions.blur-my-shell.panel]\n    blur=false\n\n    [org.gnome.shell.extensions.blur-my-shell.window-list]\n    blur=true\n    brightness=0.59999999999999998\n    sigma=30\n\n    [org.gnome.shell.extensions.blur-my-shell.applications]\n    blur=false\n\n    [org.gnome.shell.extensions.blur-my-shell]\n    pipelines={'pipeline_default': {'name': <'Default'>, 'effects': <[<{'type': <'native_static_gaussian_blur'>, 'id': <'effect_06304838404041'>, 'params': <@a{sv} {}>}>]>}, 'pipeline_default_rounded': {'name': <'Default rounded'>, 'effects': <[<{'type': <'native_static_gaussian_blur'>, 'id': <'effect_000000000001'>, 'params': <{'radius': <30>, 'brightness': <0.59999999999999998>}>}>, <{'type': <'corner'>, 'id': <'effect_000000000002'>, 'params': <{'radius': <24>}>}>]>}}\n\n    [org.gnome.shell.extensions.clipboard-history]\n    confirm-clear=false\n    paste-on-selection=false\n\n    # 1st - If the ambient light sensor functionality is enabled.\n    [org.gnome.settings-daemon.plugins.power]\n    ambient-enabled=false\n    idle-dim=true\n    power-saver-profile-on-low-battery=true\n    sleep-inactive-ac-type='nothing'\n\n    [org.gnome.settings-daemon.plugins.color]\n    night-light-schedule-automatic=true\n    night-light-temperature=3013\n";

    extraGSettingsOverridePackages = [
      pkgs.gsettings-desktop-schemas # for org.gnome.desktop
      pkgs.gnome-shell # for org.gnome.shell
      pkgs.gnome-settings-daemon # for org.gnome.settings-daemon
    ];
  };
}
